In [29]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [25]:
df = pd.read_csv('Iris.csv')
print("Dataset Preview")
print(df.head())

Dataset Preview
   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [26]:
print("\nDataset Information")
print(df.info())


Dataset Information
<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    str    
dtypes: float64(4), int64(1), str(1)
memory usage: 7.2 KB
None


In [28]:
# X = df.iloc[:, 1:-1].values
X = df.drop(['Id', 'Species'], axis=1).values
y=df.iloc[:, -1].values

label_encoder = LabelEncoder()

print("\nEncoding Target Variable")
label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)
one_hot_encoder = OneHotEncoder(sparse_output=False)
y_one_hot = one_hot_encoder.fit_transform(y_encoded.reshape(-1, 1))

print("\nUnique Classes in Target Variable")
print(np.unique(y))

print("\nEncoded Classes")
print(np.unique(y_encoded))

print("\nEncoded Target Variable (One-Hot)")
print(y_one_hot[:5])


Encoding Target Variable

Unique Classes in Target Variable
['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

Encoded Classes
[0 1 2]

Encoded Target Variable (One-Hot)
[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y_one_hot, test_size=0.2, random_state=42, stratify=y_one_hot)

print("\nShapes")
print("X_train:", X_train.shape, "y_train:", y_train.shape)
print("X_test:", X_test.shape, "y_test:", y_test.shape)


Shapes
X_train: (120, 4) y_train: (120, 3)
X_test: (30, 4) y_test: (30, 3)
